import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { searchYgoProDeck } from './providers/ygoprodeck.mjs';
import { normalizeMarketRecord, withTwd } from './providers/normalize.mjs';
import { catalogProvidersNeedingSync, syncCatalog } from './providers/catalog-sync.mjs';

const nativeFetch = globalThis.fetch;
const fetch = (url, options={}) => nativeFetch(url,{...options,signal:options.signal||AbortSignal.timeout(12000)});

const root = fileURLToPath(new URL('.', import.meta.url));
const port = Number(process.env.PORT || 4173);
const jpyToTwdFallback = Number(process.env.JPY_TO_TWD || 0.22);
const usdToTwdFallback = Number(process.env.USD_TO_TWD || 32);
const FX_CACHE_MS = 24 * 60 * 60 * 1000;
const MARKET_CACHE_MS = 24 * 60 * 60 * 1000;
const fxCache = { data:null, expiresAt:0 };
const ebaySearchCache = new Map();
const justTcgCache = new Map();
const EBAY_MARKETPLACES = new Set(['EBAY_US','EBAY_CA','EBAY_GB','EBAY_DE','EBAY_FR','EBAY_IT','EBAY_ES','EBAY_AU']);

const types = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
const json = (res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body));};
let ebayToken={value:null,expiresAt:0};

const providerStatus=()=>({
  justtcg:{enabled:false,capability:'已停用，不再作為搜尋或卡盒資料依賴'},
  ebay:{enabled:false,capability:'已停用，不再自動查詢掛牌資料'},
  ygoprodeck:{enabled:true,capability:'免費遊戲王卡片資料與跨平台最低參考價（24 小時快取；圖片需自行保存）'},
  kapaipai:{enabled:false,capability:'等待公開頁面結構與存取方式確認'},
  snkrdunk:{enabled:false,capability:'等待公開頁面結構與存取方式確認'},
  yuyutei:{enabled:Boolean(process.env.SCRAPE_SECRET),capability:'遊々亭買取行情；建議每日排程一次'},
  reportsDb:{enabled:Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_KEY),capability:'Supabase：回報、多語名稱、日版行情、匯率'}
});

function supabaseConfigured(){return Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_KEY)}
async function supabaseFetch(pathAndQuery,options={}){
  const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_KEY;
  if(!base||!key) throw new Error('SUPABASE_NOT_CONFIGURED');
  const response=await fetch(`${base}/rest/v1${pathAndQuery}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});
  if(!response.ok){const text=await response.text().catch(()=>'');throw new Error(`SUPABASE_${response.status}:${text.slice(0,200)}`)}
  const text=await response.text(); if(!text)return null; try{return JSON.parse(text)}catch{return null}
}

async function loadStoredTwdRates(){
  try{
    const rows=await supabaseFetch('/exchange_rates?select=currency,rate_to_twd,rate_date,source,fetched_at&order=fetched_at.desc&limit=30');
    if(!Array.isArray(rows)||!rows.length)return null;
    const latest=new Map(); for(const row of rows)if(!latest.has(row.currency))latest.set(row.currency,row);
    if(!['JPY','USD','EUR'].every(c=>latest.has(c)))return null;
    const times=[...latest.values()].map(r=>new Date(r.fetched_at).getTime()).filter(Number.isFinite).sort((a,b)=>b-a);
    if(!times[0]||Date.now()-times[0]>=FX_CACHE_MS)return null;
    const rates={TWD:1}; for(const [currency,row] of latest){const rate=Number(row.rate_to_twd);if(Number.isFinite(rate)&&rate>0)rates[currency]=rate}
    return {rates,updatedAt:latest.get('JPY')?.rate_date||null,fetchedAt:new Date(times[0]).toISOString(),source:`Supabase cache (${latest.get('JPY')?.source||'unknown'})`};
  }catch{return null}
}
async function saveTwdRates(data){
  if(!supabaseConfigured())return;
  const rateDate=data.updatedAt||new Date().toISOString().slice(0,10),fetchedAt=data.fetchedAt||new Date().toISOString();
  const rows=Object.entries(data.rates).filter(([c])=>c!=='TWD').map(([currency,rate])=>({currency,rate_to_twd:Number(rate),rate_date:rateDate,source:data.source,fetched_at:fetchedAt}));
  await supabaseFetch('/exchange_rates?on_conflict=currency,rate_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows)});
}
async function getTwdRates(){
  if(fxCache.data&&fxCache.expiresAt>Date.now())return fxCache.data;
  if(supabaseConfigured()){const stored=await loadStoredTwdRates();if(stored){fxCache.data=stored;fxCache.expiresAt=Date.now()+Math.max(60000,FX_CACHE_MS-(Date.now()-new Date(stored.fetchedAt).getTime()));return stored}}
  const fallback={rates:{TWD:1,JPY:jpyToTwdFallback,USD:usdToTwdFallback,EUR:35},updatedAt:null,fetchedAt:new Date().toISOString(),source:'fallback'};
  try{
    const response=await fetch('https://api.frankfurter.dev/v1/latest?base=TWD&symbols=JPY,USD,EUR'); if(!response.ok)throw new Error(`FX_${response.status}`);
    const body=await response.json(),rates={TWD:1}; for(const [currency,perTwd] of Object.entries(body.rates||{})){const value=Number(perTwd);if(Number.isFinite(value)&&value>0)rates[currency]=1/value}
    const data={rates,updatedAt:body.date||null,fetchedAt:new Date().toISOString(),source:'Frankfurter'};fxCache.data=data;fxCache.expiresAt=Date.now()+FX_CACHE_MS;saveTwdRates(data).catch(()=>{});return data;
  }catch{fxCache.data=fallback;fxCache.expiresAt=Date.now()+60*60*1000;return fallback}
}
function amountToTwd(amount,currency,fx){const value=Number(amount),rate=Number(fx?.rates?.[currency]);return Number.isFinite(value)&&Number.isFinite(rate)?Math.round(value*rate):null}

async function getEbayToken(){
  if(ebayToken.value&&Date.now()<ebayToken.expiresAt)return ebayToken.value;
  const id=process.env.EBAY_CLIENT_ID,secret=process.env.EBAY_CLIENT_SECRET;if(!id||!secret)throw new Error('EBAY_NOT_CONFIGURED');
  const auth=Buffer.from(`${id}:${secret}`).toString('base64');const response=await fetch('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials&scope=https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope'});if(!response.ok)throw new Error(`EBAY_AUTH_${response.status}`);const body=await response.json();ebayToken={value:body.access_token,expiresAt:Date.now()+Math.max(60,body.expires_in-60)*1000};return ebayToken.value;
}
async function searchEbay(query,marketplace='EBAY_US'){
  if(!EBAY_MARKETPLACES.has(marketplace))throw new Error('EBAY_MARKETPLACE_NOT_SUPPORTED');const cacheKey=`${marketplace}:${query.trim().toLowerCase()}`,cached=ebaySearchCache.get(cacheKey);if(cached&&cached.expiresAt>Date.now())return cached.data;
  const token=await getEbayToken(),url=new URL('https://api.ebay.com/buy/browse/v1/item_summary/search');url.searchParams.set('q',query);url.searchParams.set('limit','10');const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'X-EBAY-C-MARKETPLACE-ID':marketplace}});if(!response.ok)throw new Error(`EBAY_SEARCH_${response.status}`);const body=await response.json(),fx=await getTwdRates();
  const data=(body.itemSummaries||[]).map(item=>{const shipping=item.shippingOptions?.[0]?.shippingCost,priceTwd=amountToTwd(item.price?.value,item.price?.currency,fx),shippingTwd=amountToTwd(shipping?.value,shipping?.currency,fx);return {source:'eBay',marketplace,type:'掛牌',title:item.title,price:item.price?.value,currency:item.price?.currency,priceTwd,condition:item.condition,url:item.itemWebUrl,image:item.image?.imageUrl,shipping,shippingTwd,landedPriceTwd:priceTwd==null?null:priceTwd+(shippingTwd||0),observedAt:new Date().toISOString()}});ebaySearchCache.set(cacheKey,{data,expiresAt:Date.now()+MARKET_CACHE_MS});return data;
}
async function justTcg(path,params={}){const key=process.env.JUSTTCG_API_KEY;if(!key)throw new Error('JUSTTCG_NOT_CONFIGURED');const url=new URL(`https://api.justtcg.com/v1${path}`);for(const [name,value]of Object.entries(params))if(value)url.searchParams.set(name,value);const cacheKey=url.toString(),cached=justTcgCache.get(cacheKey);if(cached&&cached.expiresAt>Date.now())return cached.data;const response=await fetch(url,{headers:{'x-api-key':key}});if(!response.ok)throw new Error(`JUSTTCG_${response.status}`);const data=await response.json();justTcgCache.set(cacheKey,{data,expiresAt:Date.now()+MARKET_CACHE_MS});return data}

const EXTERNAL_QUERY_ALIASES={
  '噴火龍':{query:'Charizard',game:'pokemon'},'喷火龙':{query:'Charizard',game:'pokemon'},'charizard':{query:'Charizard',game:'pokemon'},'リザードン':{query:'Charizard',game:'pokemon'},'리자몽':{query:'Charizard',game:'pokemon'},
  '超夢':{query:'Mewtwo',game:'pokemon'},'超梦':{query:'Mewtwo',game:'pokemon'},'mewtwo':{query:'Mewtwo',game:'pokemon'},'ミュウツー':{query:'Mewtwo',game:'pokemon'},'뮤츠':{query:'Mewtwo',game:'pokemon'},
  '夢幻':{query:'Mew',game:'pokemon'},'梦幻':{query:'Mew',game:'pokemon'},'mew':{query:'Mew',game:'pokemon'},'ミュウ':{query:'Mew',game:'pokemon'},'뮤':{query:'Mew',game:'pokemon'},
  '魯夫':{query:'Luffy',game:'one-piece'},'路飛':{query:'Luffy',game:'one-piece'},'路飞':{query:'Luffy',game:'one-piece'}
};
const normalizeSearch=s=>String(s||'').toLocaleLowerCase().normalize('NFKC').replace(/[\s・·._:：'’"\-]/g,'');
const externalAliasIndex=new Map(Object.entries(EXTERNAL_QUERY_ALIASES).map(([alias,value])=>[normalizeSearch(alias),value]));
const decodeHtml=s=>String(s||'').replace(/&#039;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,'&');
async function searchOnePieceOfficial(query){const response=await nativeFetch('https://asia-en.onepiece-cardgame.com/cardlist/',{headers:{'User-Agent':'CardScope/1.0','Accept-Language':'en'},signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`ONEPIECE_${response.status}`);const html=await response.text(),needle=String(query).toLowerCase(),cards=[],seen=new Set(),re=/<a class="modalOpen"[\s\S]*?data-src="([^"]+\/images\/cardlist\/card\/([^"]+?\.png)[^"]*)"[^>]*alt="([^"]+)"[^>]*><\/a>\s*<dl[\s\S]*?<div class="infoCol">\s*<span>([^<]+)<\/span>\s*\|\s*<span>([^<]+)<\/span>\s*\|\s*<span>([^<]+)<\/span>[\s\S]*?<div class="cardName">([^<]+)<\/div>/g;let m;while((m=re.exec(html))&&cards.length<12){const name=decodeHtml(m[7]),key=`${m[4]}:${m[2]}`;if(seen.has(key)||(!name.toLowerCase().includes(needle)&&!String(m[4]).toLowerCase().includes(needle)))continue;seen.add(key);cards.push({source:'onepiece-official',providerCardId:m[4],name,game:'ONE PIECE Card Game',set:'Official card list',number:m[4],rarity:m[5],cardType:m[6],imageUrl:new URL(m[1],'https://asia-en.onepiece-cardgame.com/cardlist/').href,sourceUrl:'https://asia-en.onepiece-cardgame.com/cardlist/',priceType:'catalog'})}return cards}
async function searchExternalCatalog(query){
  const cleanQuery=String(query).trim(),mapped=externalAliasIndex.get(normalizeSearch(cleanQuery))||{query:cleanQuery,game:''},sources=[];
  if(!mapped.game||mapped.game==='pokemon')try{const apiUrl=new URL('https://api.pokemontcg.io/v2/cards');apiUrl.searchParams.set('q',`name:${mapped.query.replace(/[^a-zA-Z0-9 '\-]/g,'')}`);apiUrl.searchParams.set('pageSize','12');apiUrl.searchParams.set('select','id,name,images,set,number,rarity');const response=await nativeFetch(apiUrl,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(30000)});if(response.ok){const body=await response.json(),cards=(body.data||[]).map(card=>({source:'pokemontcg',providerCardId:card.id,name:card.name,game:'Pokemon',set:card.set?.name,number:card.number,rarity:card.rarity,imageUrl:card.images?.small||null,setLogoUrl:card.set?.images?.logo||null,priceType:'catalog'}));sources.push({source:'pokemontcg',status:'ok'});if(cards.length)return {cards,sources,query:mapped.query}}}catch(error){sources.push({source:'pokemontcg',status:'unavailable',error:error.message})}
  if(!mapped.game||mapped.game==='yugioh')try{const cards=(await searchYgoProDeck(mapped.query,{limit:12})).map(card=>({...card,source:'ygoprodeck'}));sources.push({source:'ygoprodeck',status:'ok'});if(cards.length)return {cards,sources,query:mapped.query}}catch(error){sources.push({source:'ygoprodeck',status:'unavailable',error:error.message})}
  if(!mapped.game||mapped.game==='one-piece')try{const cards=await searchOnePieceOfficial(mapped.query);sources.push({source:'onepiece-official',status:'ok'});if(cards.length)return {cards,sources,query:mapped.query}}catch(error){sources.push({source:'onepiece-official',status:'unavailable',error:error.message})}
  return {cards:[],sources,query:mapped.query}
}
async function supabaseFetchAll(pathAndQuery,pageSize=1000){const rows=[];for(let offset=0;;offset+=pageSize){const separator=pathAndQuery.includes('?')?'&':'?',batch=await supabaseFetch(`${pathAndQuery}${separator}limit=${pageSize}&offset=${offset}`);rows.push(...(batch||[]));if(!batch||batch.length<pageSize)return rows}}
async function loadPokemonSets(){const url='https://api.pokemontcg.io/v2/sets?pageSize=250&orderBy=-releaseDate',response=await nativeFetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`POKEMON_SETS_${response.status}`);const body=await response.json();return (body.data||[]).map(s=>({id:`pokemon-${s.id}`,game:'pokemon',name:s.name,nameZh:null,region:'US',language:'en-US',versionLabel:'美版',releaseDate:s.releaseDate?.replaceAll('/','-')||null,sealedCount:null,cardsCount:Number(s.total)||0,imageUrl:s.images?.logo||null,imageKind:'series-logo',symbolUrl:s.images?.symbol||null,productType:'系列',source:'pokemontcg',sourceUrl:'https://www.pokemontcg.io/'}))}
async function loadYugiohSets(){const response=await fetch('https://db.ygoprodeck.com/api/v7/cardsets.php',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`YGO_SETS_${response.status}`);const body=await response.json();return (body||[]).map((s,i)=>({id:`yugioh-${s.set_code}-${i}`,game:'yugioh',name:s.set_name,nameZh:null,region:'US',language:'en-US',versionLabel:'美版',releaseDate:s.tcg_date||null,sealedCount:null,cardsCount:Number(s.num_of_cards)||0,imageUrl:s.set_image||null,imageKind:'series-logo',productType:'系列',source:'ygoprodeck',sourceUrl:'https://ygoprodeck.com/'}))}
async function loadOnePieceProducts(){const response=await fetch('https://asia-en.onepiece-cardgame.com/products/',{headers:{'User-Agent':'CardScope/1.0','Accept-Language':'en'}});if(!response.ok)throw new Error(`ONEPIECE_PRODUCTS_${response.status}`);const html=await response.text(),items=[],re=/<li class="linkListColBox" data-cat="([^"]+)">[\s\S]*?<a href="([^"]+)" class="linkListColItem">[\s\S]*?<img[^>]+data-src="([^"]+)"[^>]*>[\s\S]*?<h4 class="linkListColTitle">([\s\S]*?)<\/h4>[\s\S]*?<time[^>]+datetime="([^"]+)"/g;let m;while((m=re.exec(html))){items.push({id:`onepiece-${items.length}`,game:'onepiece',name:decodeHtml(m[4].replace(/<[^>]+>/g,'').trim()),nameZh:null,region:'ASIA',language:'en',versionLabel:'亞洲英文版',productType:m[1],releaseDate:m[5],sealedCount:null,cardsCount:null,imageUrl:new URL(m[3],'https://asia-en.onepiece-cardgame.com/').href,imageKind:'sealed-product',source:'onepiece-official',sourceUrl:new URL(m[2],'https://asia-en.onepiece-cardgame.com/').href})}return items}
async function loadCuratedProducts(){const catalog=await loadFallbackCatalog();return catalog.series.map(s=>({id:`curated-${s.id}`,game:s.game,name:s.nameEn||s.nameJa||s.nameZh,nameZh:s.nameZh,nameJa:s.nameJa,nameKo:s.nameKo||null,officialCode:s.officialCode,region:s.region,language:s.region==='JP'?'ja-JP':s.region==='KR'?'ko-KR':s.region==='TW'?'zh-Hant-TW':'en-US',versionLabel:null,releaseDate:s.releaseDate,sealedCount:null,cardsCount:null,imageUrl:null,imageKind:null,productType:'系列',source:'curated-official-index',sourceUrl:s.sourceUrl||null}))}
async function loadStoredProducts(){if(!supabaseConfigured())return [];const rows=await supabaseFetchAll('/tcg_products?select=id,game:game_id,seriesId:series_id,officialCode:official_code,productType:product_type,nameZh:name_zh,nameJa:name_ja,name:name_en,nameKo:name_ko,region,language,releaseDate:release_date,imageUrl:image_url,imageKind:image_kind,source,sourceUrl:source_url,metadata&order=release_date.desc.nullslast');return rows.map(row=>({...row,versionLabel:regionLabel(row.region,row.language),cardsCount:row.metadata?.cardsCount??row.metadata?.total??null}))}
async function loadProductSets(){const stored=await loadStoredProducts().catch(()=>[]),settled=stored.length?[{status:'fulfilled',value:stored}, {status:'fulfilled',value:await loadCuratedProducts()}]:await Promise.allSettled([loadCuratedProducts(),loadPokemonSets(),loadYugiohSets(),loadOnePieceProducts()]),seen=new Set(),excluded=/playmat|sleeve|storage|binder|portfolio|deck case|card case/i;return settled.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(x=>{if(!['sealed-product','series-logo'].includes(x.imageKind)&&x.imageUrl)return false;if(x.imageKind==='sealed-product'&&excluded.test(`${x.productType||''} ${x.name||''}`))return false;const key=`${x.game}:${x.region}:${x.officialCode||x.name}`;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>String(b.releaseDate||'').localeCompare(String(a.releaseDate||'')))}
function regionLabel(region,language){if(region==='JP')return '日版';if(region==='TW')return '台版';if(region==='KR')return '韓版';if(region==='US')return '美版';if(region==='ASIA'&&String(language).startsWith('en'))return '亞洲英文版';return region||language||'版本待確認'}

let fallbackCatalogCache=null;
async function loadFallbackCatalog(){if(!fallbackCatalogCache)fallbackCatalogCache=JSON.parse(await readFile(join(root,'data','catalog.json'),'utf8'));return structuredClone(fallbackCatalogCache)}
const uniqueValues=(...groups)=>[...new Set(groups.flat().filter(Boolean).map(String))];
function mergeCatalogRows(fallbackRows=[],databaseRows=[]){
  const rows=new Map(fallbackRows.map(row=>[row.id,structuredClone(row)]));
  for(const row of databaseRows){const fallback=rows.get(row.id)||{},merged={...fallback,...row};for(const key of ['nameZh','nameJa','nameEn','nameKo','imageUrl','imageSource','sourceUrl'])if(!merged[key])merged[key]=fallback[key]||null;merged.aliases=uniqueValues(fallback.aliases||[],row.aliases||[]);merged.printings=[...(fallback.printings||[]),...(row.printings||[])];rows.set(row.id,merged)}
  return [...rows.values()];
}
function canonicalizeCatalog(catalog){
  const grouped=new Map();
  for(const physical of catalog.cards||[]){
    const canonicalId=physical.canonicalId||physical.id,existing=grouped.get(canonicalId),derivedPrinting={cardId:physical.id,region:physical.region||null,language:physical.language||null,localSetCode:physical.localSetCode||null,localCardNumber:physical.officialCardNumber||null,imageUrl:physical.imageUrl||null,sourceUrl:physical.sourceUrl||null,releaseDate:physical.releaseDate||null,seriesId:physical.seriesId||null,rarity:physical.rarity||null,nameZh:physical.nameZh||null,nameJa:physical.nameJa||null,nameEn:physical.nameEn||null,nameKo:physical.nameKo||null},printings=(physical.printings?.length?physical.printings:[derivedPrinting]).map(p=>({...derivedPrinting,...p,cardId:p.cardId||physical.id,seriesId:p.seriesId||physical.seriesId||null,localCardNumber:p.localCardNumber||physical.officialCardNumber||null,imageUrl:p.imageUrl||physical.imageUrl||null}));
    if(!existing){grouped.set(canonicalId,{...physical,id:canonicalId,canonicalId,physicalCardIds:[physical.id],aliases:uniqueValues(physical.aliases||[],physical.nameZh,physical.nameJa,physical.nameEn,physical.nameKo),printings,region:printings[0]?.region||physical.region||null,language:printings[0]?.language||physical.language||null,imageUrl:physical.imageUrl||printings.find(p=>p.imageUrl)?.imageUrl||null});continue}
    existing.physicalCardIds=uniqueValues(existing.physicalCardIds,physical.id);existing.aliases=uniqueValues(existing.aliases,physical.aliases||[],physical.nameZh,physical.nameJa,physical.nameEn,physical.nameKo);existing.printings.push(...printings);for(const key of ['nameZh','nameJa','nameEn','nameKo','imageUrl','imageSource'])if(!existing[key]&&physical[key])existing[key]=physical[key];
  }
  for(const card of grouped.values()){const seen=new Set();card.printings=card.printings.filter(p=>{const key=[p.cardId,p.region,p.language,p.localSetCode,p.localCardNumber].join('|');if(seen.has(key))return false;seen.add(key);return true});card.imageUrl=card.imageUrl||card.printings.find(p=>p.imageUrl)?.imageUrl||null}
  return {...catalog,cards:[...grouped.values()]};
}
async function loadCatalog(){
  const fallback=await loadFallbackCatalog();
  if(!supabaseConfigured())return canonicalizeCatalog({...fallback,source:'catalog.json'});
  try{
    const [games,series,cards,printings,images]=await Promise.all([
      supabaseFetch('/tcg_games?select=id,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko&order=id'),
      supabaseFetchAll('/tcg_series?select=id,game:game_id,officialCode:official_code,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko,region,language,releaseDate:release_date,aliases,sourceUrl:source_url,imageUrl:image_url,imageKind:image_kind&order=release_date.desc'),
      supabaseFetch('/tcg_cards?select=id,canonicalId:canonical_id,game:game_id,seriesId:series_id,officialCardNumber:official_card_number,rarity,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko,aliases&order=created_at.asc&limit=250'),
      supabaseFetch('/tcg_printings?select=id,cardId:card_id,seriesId:series_id,region,language,localSetCode:local_set_code,localCardNumber:local_card_number,rarity,imageUrl:image_url,sourceUrl:source_url,releaseDate:release_date,imageRehostRequired:image_rehost_required&order=created_at.asc&limit=1000'),
      supabaseFetch('/card_images?select=cardId:card_id,language,source,imageUrl:image_url,sourceUrl:source_url,isPrimary:is_primary,fetchedAt:fetched_at&order=is_primary.desc,fetched_at.desc').catch(()=>[])
    ]);
    const printingByCard=new Map(),imageByCard=new Map();
    for(const p of printings||[]){const list=printingByCard.get(p.cardId)||[];list.push(p);printingByCard.set(p.cardId,list)}
    for(const i of images||[]){const list=imageByCard.get(i.cardId)||[];list.push(i);imageByCard.set(i.cardId,list)}
    const databaseCards=(cards||[]).map(c=>{const ps=printingByCard.get(c.id)||[],imgs=imageByCard.get(c.id)||[],primary=imgs[0]||ps.find(p=>p.imageUrl);return {...c,region:ps[0]?.region||null,language:ps[0]?.language||null,imageUrl:primary?.imageUrl||null,imageSource:primary?.source||null,printings:ps,images:imgs}}),merged={version:3,updatedAt:new Date().toISOString(),source:'supabase+catalog.json',games:mergeCatalogRows(fallback.games,games||[]),series:mergeCatalogRows(fallback.series,series||[]),cards:mergeCatalogRows(fallback.cards,databaseCards)};
    return canonicalizeCatalog(merged);
  }catch(error){return canonicalizeCatalog({...fallback,source:'catalog.json',fallbackReason:error.message})}
}
async function fetchCardIdentities({query,cardNumber,limit=10}){const catalog=await loadCatalog(),needle=normalizeSearch(query),numberNeedle=normalizeSearch(cardNumber);return catalog.cards.filter(card=>{const names=[card.nameZh,card.nameJa,card.nameEn,card.nameKo,...(card.aliases||[]),...(card.printings||[]).flatMap(p=>[p.nameZh,p.nameJa,p.nameEn,p.nameKo])],numbers=[card.officialCardNumber,...(card.printings||[]).map(p=>p.localCardNumber)];return names.some(name=>normalizeSearch(name).includes(needle))&&(!numberNeedle||numbers.some(number=>normalizeSearch(number).includes(numberNeedle)))}).slice(0,limit).map(card=>({id:card.id,canonicalId:card.canonicalId,cardNumber:card.officialCardNumber,game:card.game,seriesId:card.seriesId,rarity:card.rarity,nameZh:card.nameZh,nameJa:card.nameJa,nameEn:card.nameEn,nameKo:card.nameKo,aliases:card.aliases,printings:card.printings}))}

const postgrestLike=s=>String(s||'').replace(/[\\%_*(),.]/g,'').trim();
async function searchCatalogDatabase(rawQuery,region='ALL',limit=40){
  if(!supabaseConfigured())return [];
  const mapped=externalAliasIndex.get(normalizeSearch(rawQuery))?.query,terms=[rawQuery,mapped].filter(Boolean).map(postgrestLike).filter(Boolean);if(!terms.length)return [];
  const select='id,canonicalId:canonical_id,game:game_id,seriesId:series_id,officialCardNumber:official_card_number,rarity,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko,aliases,searchText:search_text',query=async columns=>{const filters=[];for(const term of terms)for(const column of columns)filters.push(`${column}.ilike.*${term}*`);return supabaseFetch(`/tcg_cards?${new URLSearchParams({select,or:`(${filters.join(',')})`,limit:'100'})}`)};
  let cards=await query(['name_zh','name_ja','name_en','name_ko','official_card_number']);if(!cards?.length)cards=await query(['search_text']);if(!cards?.length)return [];
  const needles=terms.map(normalizeSearch),score=card=>{const names=[card.nameZh,card.nameJa,card.nameEn,card.nameKo,...(card.aliases||[]),card.officialCardNumber].map(normalizeSearch).filter(Boolean);if(names.some(name=>needles.some(needle=>name===needle)))return 0;if(names.some(name=>needles.some(needle=>name.startsWith(needle))))return 1;if(names.some(name=>needles.some(needle=>name.includes(needle))))return 2;return 3};cards.sort((a,b)=>score(a)-score(b)||String(a.nameEn||a.nameZh||'').localeCompare(String(b.nameEn||b.nameZh||'')));
  const ids=cards.map(c=>`"${String(c.id).replaceAll('"','')}"`).join(','),printingParams=new URLSearchParams({select:'id,cardId:card_id,seriesId:series_id,region,language,localSetCode:local_set_code,localCardNumber:local_card_number,rarity,imageUrl:image_url,sourceUrl:source_url,releaseDate:release_date,imageRehostRequired:image_rehost_required',card_id:`in.(${ids})`,limit:'1000'}),printings=await supabaseFetch(`/tcg_printings?${printingParams}`),byCard=new Map();
  for(const p of printings||[]){if(region!=='ALL'&&p.region!==region)continue;const list=byCard.get(p.cardId)||[];list.push(p);byCard.set(p.cardId,list)}
  return canonicalizeCatalog({cards:cards.filter(c=>region==='ALL'||byCard.has(c.id)).map(c=>({...c,printings:byCard.get(c.id)||[],region:byCard.get(c.id)?.[0]?.region||null,language:byCard.get(c.id)?.[0]?.language||null,imageUrl:byCard.get(c.id)?.find(p=>p.imageUrl&&!p.imageRehostRequired)?.imageUrl||null}))}).cards.slice(0,limit);
}

async function loadCardFromDatabase(cardId){
  if(!supabaseConfigured())return null;const safe=String(cardId).replace(/[(),]/g,''),params=new URLSearchParams({select:'id,canonicalId:canonical_id,game:game_id,seriesId:series_id,officialCardNumber:official_card_number,rarity,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko,aliases',or:`(id.eq.${safe},canonical_id.eq.${safe})`,limit:'100'}),cards=await supabaseFetch(`/tcg_cards?${params}`);if(!cards?.length)return null;
  const ids=cards.map(c=>`"${String(c.id).replaceAll('"','')}"`).join(','),printingParams=new URLSearchParams({select:'id,cardId:card_id,seriesId:series_id,region,language,localSetCode:local_set_code,localCardNumber:local_card_number,rarity,imageUrl:image_url,sourceUrl:source_url,releaseDate:release_date,imageRehostRequired:image_rehost_required',card_id:`in.(${ids})`,limit:'1000'}),printings=await supabaseFetch(`/tcg_printings?${printingParams}`),byCard=new Map();for(const p of printings||[]){const list=byCard.get(p.cardId)||[];list.push(p);byCard.set(p.cardId,list)}
  const hydrated=cards.map(c=>({...c,printings:byCard.get(c.id)||[],region:byCard.get(c.id)?.[0]?.region||null,language:byCard.get(c.id)?.[0]?.language||null,imageUrl:byCard.get(c.id)?.find(p=>p.imageUrl&&!p.imageRehostRequired)?.imageUrl||null})),canonical=canonicalizeCatalog({cards:hydrated}).cards.find(c=>c.id===cardId)||canonicalizeCatalog({cards:hydrated}).cards[0],seriesIds=[...new Set((canonical?.printings||[]).map(p=>p.seriesId).concat(canonical?.seriesId).filter(Boolean))],series=seriesIds.length?await supabaseFetch(`/tcg_series?select=id,game:game_id,officialCode:official_code,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko,region,releaseDate:release_date&${new URLSearchParams({id:`in.(${seriesIds.map(x=>`"${x}"`).join(',')})`})}`):[],games=await supabaseFetch(`/tcg_games?select=id,nameZh:name_zh,nameJa:name_ja,nameEn:name_en,nameKo:name_ko&id=eq.${encodeURIComponent(canonical.game)}`);return {catalog:{source:'supabase-full-catalog',cards:[canonical],series:series||[],games:games||[]},card:canonical};
}
async function getCard(cardId){const catalog=await loadCatalog(),card=catalog.cards.find(c=>c.id===cardId);if(card)return {catalog,card};try{return await loadCardFromDatabase(cardId)||{catalog,card:null}}catch{return {catalog,card:null}}}
async function yuyuteiMarket(card,fx){if(!supabaseConfigured())return [];const esc=v=>String(v).replace(/[\\%_*(),.]/g,'\\$&'),params=new URLSearchParams({select:'cardName:card_name,cardNumber:card_number,rarity,price,currency,cardUrl:card_url,imageUrl:image_url,setCode:set_code,setName:set_name,scrapedAt:scraped_at',card_number:`eq.${esc(card.officialCardNumber)}`,order:'scraped_at.desc',limit:'10'}),rows=await supabaseFetch(`/jp_buyback_prices?${params}`);return (rows||[]).map(r=>withTwd(normalizeMarketRecord({provider:'yuyutei',market:'JP',cardId:card.id,cardName:r.cardName,cardNumber:r.cardNumber,setCode:r.setCode,rarity:r.rarity,language:'ja-JP',priceType:'buyback',amount:r.price,currency:r.currency,imageUrl:r.imageUrl,sourceUrl:r.cardUrl,observedAt:r.scrapedAt}),fx))}
async function unifiedMarket(card){
  const fx=await getTwdRates(),tasks=[['yuyutei',()=>yuyuteiMarket(card,fx)]];
  if(card.game==='yugioh')tasks.push(['ygoprodeck',async()=>{const found=await searchYgoProDeck(card.nameEn||card.nameJa||card.nameZh,{limit:10}),match=found.find(x=>String(x.name).toLowerCase()===String(card.nameEn||'').toLowerCase())||found[0];if(!match)return [];return [['Cardmarket',match.referencePrices.cardmarketEur,'EUR'],['TCGplayer',match.referencePrices.tcgplayerUsd,'USD']].filter(([,amount])=>amount!=null).map(([market,amount,currency])=>withTwd(normalizeMarketRecord({provider:'ygoprodeck',market,cardId:card.id,providerCardId:match.providerCardId,cardName:match.name,cardNumber:card.officialCardNumber,priceType:'market',amount,currency,observedAt:match.observedAt}),fx))}]);
  const settled=await Promise.all(tasks.map(async([source,run])=>{try{return {source,status:'ok',data:await run()}}catch(error){return {source,status:'unavailable',error:error.message}}})),records=settled.flatMap(x=>Array.isArray(x.data)?x.data:[]);
  return {records,sources:settled.map(x=>({source:x.source,status:x.status,error:x.error||null,notice:x.data?.notice||null})),meta:{exchangeRates:fx,priceTypes:{listing:'在售掛牌',buyback:'店家買取／回收',market:'平台參考價',sale:'可驗證成交',user_report:'使用者回報（未驗證）'},warning:'不同價格性質不混算中位價；目前沒有可靠成交來源時，不顯示成交價或交易量。'}}
}

const ALLOWED_PLATFORMS=['卡拍拍','露天拍賣','蝦皮購物','露天/蝦皮以外的台灣賣場','其他'];const ALLOWED_CURRENCIES=['TWD','USD','JPY','EUR'];const MAX_PRICE=5000000;const reportRateLimit=new Map();const PUBLIC_SELECT='id,cardName:card_name,cardId:card_id,game,platform,currency,price,condition,note,tradedAt:traded_at,createdAt:created_at,status';
function hashIp(ip){return createHash('sha256').update(String(ip)).digest('hex').slice(0,16)}function clientIp(req){const fwd=req.headers['x-forwarded-for'];return fwd?fwd.split(',')[0].trim():(req.socket.remoteAddress||'unknown')}function isRateLimited(ip){const key=hashIp(ip),now=Date.now(),timestamps=(reportRateLimit.get(key)||[]).filter(t=>now-t<3600000);if(timestamps.length>=5){reportRateLimit.set(key,timestamps);return true}timestamps.push(now);reportRateLimit.set(key,timestamps);return false}
function readJsonBody(req,maxBytes=10000){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>maxBytes){reject(new Error('BODY_TOO_LARGE'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{if(!chunks.length)return resolve({});try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')))}catch{reject(new Error('INVALID_JSON'))}});req.on('error',reject)})}
function validateReport(body){const errors=[],cardName=String(body.cardName||'').trim(),cardId=body.cardId?String(body.cardId).trim():null,game=body.game?String(body.game).trim():null,platform=String(body.platform||'').trim(),currency=String(body.currency||'TWD').trim().toUpperCase(),price=Number(body.price),condition=body.condition?String(body.condition).trim().slice(0,40):null,note=body.note?String(body.note).trim().slice(0,200):null;let tradedAt=new Date().toISOString();if(!cardName||cardName.length>100)errors.push('請提供卡片名稱');if(!ALLOWED_PLATFORMS.includes(platform))errors.push('不支援的平台');if(!ALLOWED_CURRENCIES.includes(currency))errors.push('不支援的幣別');if(!Number.isFinite(price)||price<=0||price>MAX_PRICE)errors.push('價格格式錯誤');if(body.tradedAt){const d=new Date(body.tradedAt);if(isNaN(d.getTime()))errors.push('日期格式錯誤');else tradedAt=d.toISOString()}return errors.length?{valid:false,errors}:{valid:true,value:{cardName,cardId,game,platform,currency,price,condition,note,tradedAt}}}
function median(nums){const s=[...nums].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}function buildStats(rows){const groups={};for(const r of rows){(groups[r.currency]??=[]).push(Number(r.price))}const stats={};for(const [currency,p]of Object.entries(groups))stats[currency]={count:p.length,min:Math.min(...p),max:Math.max(...p),median:median(p),avg:Math.round(p.reduce((a,b)=>a+b,0)/p.length*100)/100};return stats}

async function scrapeYuyutei(targetUrl){const response=await fetch(targetUrl,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'ja,en-US;q=0.9'}});if(!response.ok)throw new Error(`FETCH_${response.status}`);const html=(await response.text()).replace(/\s+/g,' '),setTitle=html.match(/<h3 class="fw-bold py-3">\s*<span class="line1"><\/span>\s*([^<]+)<\/h3>/)?.[1]?.trim()||null,game=targetUrl.match(/\/buy\/([a-z0-9]+)\//i)?.[1]||'unknown',tokens=[];let m;const rarityRe=/<span class="py-2 d-inline-block px-2 me-2 text-white fw-bold">([^<]+)<\/span>\s*Card List/g;while((m=rarityRe.exec(html)))tokens.push({type:'rarity',index:m.index,value:m[1].trim()});const cardRe=/<div class="card-product position-relative mt-4[^"]*"/g;while((m=cardRe.exec(html)))tokens.push({type:'card',index:m.index});tokens.sort((a,b)=>a.index-b.index);const found=[];let rarity=null;for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t.type==='rarity'){rarity=t.value;continue}const end=i+1<tokens.length?tokens[i+1].index:Math.min(html.length,t.index+3000),chunk=html.slice(t.index,end),ver=chunk.match(/value="([^"]+)" class="cart_ver"/)?.[1],cid=chunk.match(/value="([^"]+)" class="cart_cid"/)?.[1],number=chunk.match(/text-center my-2">([^<]+)<\/span>/)?.[1]?.trim()||null,name=chunk.match(/text-primary fw-bold">([^<]+)<\/h4>/)?.[1]?.trim()||null,price=chunk.match(/<strong class="d-block text-end[^"]*">\s*([\d,]+)\s*円/)?.[1];if(!ver||!cid||!price)continue;found.push({setCode:ver,cardCode:cid,number,name,rarity,price:Number(price.replace(/,/g,'')),cardUrl:`https://yuyu-tei.jp/buy/${game}/card/${ver}/${cid}`,imageUrl:`https://card.yuyu-tei.jp/${game}/100_140/${ver}/${cid}.jpg`})}return {game,setTitle,cards:found}}

const server=createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);
  if(url.pathname==='/api/providers')return json(res,200,{data:providerStatus()});
  if(url.pathname==='/api/catalog'&&req.method==='GET'){const data=await loadCatalog();return json(res,200,{data,meta:{source:data.source,fallbackReason:data.fallbackReason||null}})}
  if(url.pathname==='/api/products'&&req.method==='GET'){try{const data=await loadProductSets();return json(res,200,{data,meta:{sources:['CardScope official index','Pokemon TCG API','YGOPRODeck','ONE PIECE official products'],warning:'繁體中文名稱只在有可靠對照時優先顯示；每筆保留實際地區與語言。產品與系列不是庫存或銷量。'}})}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/exchange-rates'&&req.method==='GET')return json(res,200,{data:await getTwdRates()});
  if(url.pathname==='/api/card-identities'&&req.method==='GET'){if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});const query=url.searchParams.get('q')?.trim(),cardNumber=url.searchParams.get('cardNumber')?.trim();if(!query)return json(res,400,{error:'請提供 q'});try{return json(res,200,{data:await fetchCardIdentities({query,cardNumber})||[]})}catch{return json(res,404,{error:'卡片多語對照表尚未設定'})}}
  if(url.pathname==='/api/providers/ygoprodeck/search'&&req.method==='GET'){const q=(url.searchParams.get('q')||'').trim();if(q.length<2)return json(res,400,{error:'請輸入至少兩個字元'});try{const data=await searchYgoProDeck(q,{limit:10}),fx=await getTwdRates();return json(res,200,{data:data.map(card=>({...card,referencePricesTwd:{cardmarket:amountToTwd(card.referencePrices.cardmarketEur,'EUR',fx),tcgplayer:amountToTwd(card.referencePrices.tcgplayerUsd,'USD',fx),ebay:amountToTwd(card.referencePrices.ebayUsd,'USD',fx),amazon:amountToTwd(card.referencePrices.amazonUsd,'USD',fx),coolstuffinc:amountToTwd(card.referencePrices.coolstuffincUsd,'USD',fx)}})),meta:{cacheHours:24,exchangeRates:fx,priceWarning:'跨平台最低參考價，不代表指定版本成交價'}})}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/search/external'&&req.method==='GET'){const q=(url.searchParams.get('q')||'').trim();if(q.length<2)return json(res,400,{error:'請輸入至少兩個字元'});const data=await searchExternalCatalog(q);return json(res,200,{data:data.cards,meta:{resolvedQuery:data.query,sources:data.sources,warning:'外部結果尚未匯入 CardScope Catalog；價格只作市場參考，不代表成交。'}})}
  if(url.pathname==='/api/providers/justtcg/games'){try{return json(res,200,await justTcg('/games'))}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/providers/justtcg/sets'){const game=url.searchParams.get('game')||'';try{return json(res,200,await justTcg('/sets',{game,limit:'100'}))}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/providers/justtcg/sealed'){const game=url.searchParams.get('game')||'';for(const path of ['/sealed-products','/products','/sealed']){try{return json(res,200,await justTcg(path,{game,limit:'100'}))}catch(e){if(!String(e.message).includes('_404'))return json(res,502,{error:e.message})}}return json(res,404,{error:'JustTCG 目前沒有公開 sealed product endpoint'})}
  if(url.pathname==='/api/providers/justtcg/search'){const q=(url.searchParams.get('q')||'').trim(),game=url.searchParams.get('game')||'';if(q.length<2)return json(res,400,{error:'請輸入至少兩個字元'});try{return json(res,200,await justTcg('/cards',{q,game,limit:'10',priceHistoryDuration:'30d'}))}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/providers/justtcg/cards'){const cardId=url.searchParams.get('cardId');if(!cardId)return json(res,400,{error:'請提供 cardId'});try{return json(res,200,await justTcg('/cards',{cardId,priceHistoryDuration:'30d'}))}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/providers/ebay/search'){const q=(url.searchParams.get('q')||'').trim(),marketplace=(url.searchParams.get('marketplace')||'EBAY_US').toUpperCase();if(!q)return json(res,400,{error:'請提供 q'});if(!EBAY_MARKETPLACES.has(marketplace))return json(res,400,{error:'不支援的 eBay marketplace'});try{return json(res,200,{data:await searchEbay(q,marketplace),meta:{marketplace,cacheHours:24}})}catch(e){return json(res,e.message==='EBAY_NOT_CONFIGURED'?503:502,{error:e.message})}}
  if(url.pathname==='/api/cards'&&req.method==='GET'){const catalog=await loadCatalog();return json(res,200,{data:catalog.cards,meta:{source:catalog.source}})}
  if(url.pathname==='/api/search'&&req.method==='GET'){
    const rawQ=(url.searchParams.get('q')||'').trim(),q=normalizeSearch(rawQ),region=(url.searchParams.get('region')||'all').toUpperCase(),catalog=await loadCatalog(),seriesById=new Map(catalog.series.map(s=>[s.id,s])),nameValues=c=>[c.nameZh,c.nameJa,c.nameEn,c.nameKo,...(c.aliases||[]),...(c.printings||[]).flatMap(p=>[p.nameZh,p.nameJa,p.nameEn,p.nameKo])];
    const found=catalog.cards.filter(c=>{if(region!=='ALL'&&c.region!==region&&!c.printings?.some(p=>p.region===region))return false;const series=[seriesById.get(c.seriesId)||{},...(c.printings||[]).map(p=>seriesById.get(p.seriesId)||{})],values=[...nameValues(c),c.officialCardNumber,...(c.printings||[]).flatMap(p=>[p.localSetCode,p.localCardNumber]),...series.flatMap(s=>[s.officialCode,s.nameZh,s.nameJa,s.nameEn,s.nameKo,...(s.aliases||[])])];return !q||values.some(v=>normalizeSearch(v).includes(q))}),exact=q?found.filter(c=>nameValues(c).some(v=>normalizeSearch(v)===q)):[];
    if(exact.length)return json(res,200,{data:exact,meta:{source:catalog.source,architecture:'canonical-card-with-printings',match:'exact-name'}});
    try{const database=await searchCatalogDatabase(rawQ,region);if(database.length)return json(res,200,{data:database,meta:{source:'supabase-full-catalog',architecture:'canonical-card-with-printings',match:'database-substring'}})}catch(error){console.error('catalog search failed',error.message)}
    return json(res,200,{data:found,meta:{source:catalog.source,architecture:'canonical-card-with-printings',match:'substring'}})
  }
  if(url.pathname.startsWith('/api/cards/')&&req.method==='GET'){const tail=decodeURIComponent(url.pathname.slice(11));if(tail.endsWith('/market')){const id=tail.slice(0,-7),{card}=await getCard(id);if(!card)return json(res,404,{error:'找不到這張卡'});return json(res,200,{data:await unifiedMarket(card)})}const {catalog,card}=await getCard(tail);if(!card)return json(res,404,{error:'找不到這張卡'});const series=catalog.series.find(s=>s.id===card.seriesId)||null,game=catalog.games.find(g=>g.id===card.game)||null;return json(res,200,{data:{...card,series,game},meta:{source:catalog.source,imagePolicy:'優先使用已保存或來源允許的圖片；不長期 hotlink YGOPRODeck 圖片。'}})}
  if(url.pathname==='/api/portfolio')return json(res,200,{data:null,meta:{status:'not_implemented',message:'尚未有真實收藏資料，因此不顯示示範市值或損益。'}});
  if(url.pathname==='/api/reports/meta')return json(res,200,{data:{platforms:ALLOWED_PLATFORMS,currencies:ALLOWED_CURRENCIES,maxPrice:MAX_PRICE}});
  if(url.pathname==='/api/reports'&&req.method==='POST'){if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});if(isRateLimited(clientIp(req)))return json(res,429,{error:'回報太頻繁'});let body;try{body=await readJsonBody(req)}catch{return json(res,400,{error:'JSON 格式錯誤'})}const v=validateReport(body);if(!v.valid)return json(res,400,{error:'資料驗證失敗',details:v.errors});const r=v.value,record={card_name:r.cardName,card_id:r.cardId,game:r.game,platform:r.platform,currency:r.currency,price:r.price,condition:r.condition,note:r.note,traded_at:r.tradedAt,reporter_hash:hashIp(clientIp(req)),status:'unverified'};try{const rows=await supabaseFetch('/reports?select='+encodeURIComponent(PUBLIC_SELECT),{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([record])});return json(res,201,{data:rows?.[0]})}catch{return json(res,502,{error:'資料庫寫入失敗'})}}
  if(url.pathname==='/api/reports'&&req.method==='GET'){if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});const cardId=url.searchParams.get('cardId'),cardName=url.searchParams.get('cardName'),game=url.searchParams.get('game'),limit=Math.min(Number(url.searchParams.get('limit'))||20,100);if(!cardId&&!cardName)return json(res,400,{error:'請提供 cardId 或 cardName'});const base=new URLSearchParams();if(cardId)base.set('card_id',`eq.${cardId}`);else base.set('card_name',`ilike.*${cardName}*`);if(game)base.set('game',`eq.${game}`);try{const statsParams=new URLSearchParams(base);statsParams.set('select','currency,price');const recentParams=new URLSearchParams(base);recentParams.set('select',PUBLIC_SELECT);recentParams.set('order','traded_at.desc');recentParams.set('limit',String(limit));const [all,recent]=await Promise.all([supabaseFetch(`/reports?${statsParams}`),supabaseFetch(`/reports?${recentParams}`)]);return json(res,200,{data:{reports:recent,stats:buildStats(all),total:all.length}})}catch{return json(res,502,{error:'資料庫查詢失敗'})}}
  if(url.pathname==='/api/admin/scrape/yuyutei'&&(req.method==='POST'||req.method==='GET')){const token=req.headers['x-scrape-token']||url.searchParams.get('token');if(!process.env.SCRAPE_SECRET||token!==process.env.SCRAPE_SECRET)return json(res,401,{error:'未授權'});if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});let targetUrl=url.searchParams.get('url');if(req.method==='POST'){try{targetUrl=(await readJsonBody(req)).url||targetUrl}catch{return json(res,400,{error:'JSON 格式錯誤'})}}if(!targetUrl?.startsWith('https://yuyu-tei.jp/buy/'))return json(res,400,{error:'請提供合法的遊々亭買取頁'});try{const {game,setTitle,cards:found}=await scrapeYuyutei(targetUrl),rows=found.map(c=>({source:'yuyutei',game,set_code:c.setCode,set_name:setTitle,card_code:c.cardCode,card_number:c.number,rarity:c.rarity,card_name:c.name,price:c.price,currency:'JPY',card_url:c.cardUrl,image_url:c.imageUrl,scraped_at:new Date().toISOString()}));for(let i=0;i<rows.length;i+=200)await supabaseFetch('/jp_buyback_prices?on_conflict=source,game,set_code,card_code',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows.slice(i,i+200))});return json(res,200,{data:{message:'抓取並存檔成功',game,setTitle,count:rows.length}})}catch(e){return json(res,502,{error:`抓取失敗：${e.message}`})}}
  if(url.pathname==='/api/catalog/sync-status'&&req.method==='GET'){if(!supabaseConfigured())return json(res,200,{data:[]});try{const data=await supabaseFetch('/catalog_sync_runs?select=provider,scope,status,rowsSeen:rows_seen,rowsWritten:rows_written,error,metadata,startedAt:started_at,finishedAt:finished_at&order=started_at.desc&limit=12');return json(res,200,{data})}catch(e){return json(res,502,{error:e.message})}}
  if(url.pathname==='/api/admin/catalog/sync'&&req.method==='POST'){const token=req.headers['x-scrape-token']||url.searchParams.get('token');if(!process.env.SCRAPE_SECRET||token!==process.env.SCRAPE_SECRET)return json(res,401,{error:'未授權'});if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});const requested=(url.searchParams.get('provider')||'all').toLowerCase(),providers=requested==='all'?['pokemon','onepiece','yugioh']:[requested];if(providers.some(p=>!['pokemon','onepiece','yugioh'].includes(p)))return json(res,400,{error:'不支援的 provider'});syncCatalog(supabaseFetch,{providers}).then(result=>console.log('catalog sync complete',JSON.stringify(result))).catch(error=>console.error('catalog sync failed',error));return json(res,202,{data:{message:'Catalog 同步已在背景開始',providers}})}
  if(url.pathname==='/api/jp-prices'&&req.method==='GET'){if(!supabaseConfigured())return json(res,503,{error:'尚未設定資料庫'});const cardName=url.searchParams.get('cardName')?.trim(),cardNumber=url.searchParams.get('cardNumber')?.trim(),aliases=url.searchParams.getAll('alias').filter(Boolean);if(!cardName)return json(res,400,{error:'請提供 cardName'});const esc=v=>v.replace(/[\\%_*(),.]/g,'\\$&'),matches=[cardName,...aliases].slice(0,10).map(n=>`card_name.ilike.*${esc(n)}*`);if(cardNumber)matches.push(`card_number.ilike.*${esc(cardNumber)}*`);const params=new URLSearchParams({select:'game,cardName:card_name,cardCode:card_code,cardNumber:card_number,rarity,price,currency,cardUrl:card_url,imageUrl:image_url,setName:set_name,scrapedAt:scraped_at',or:`(${matches.join(',')})`,order:'scraped_at.desc',limit:'5'});try{const rows=await supabaseFetch(`/jp_buyback_prices?${params}`),fx=await getTwdRates();return json(res,200,{data:(rows||[]).map(r=>({...r,priceType:'buyback',priceTwd:amountToTwd(r.price,r.currency,fx)})),meta:{exchangeRates:fx}})}catch{return json(res,502,{error:'查詢失敗'})}}
  let pathname=url.pathname==='/'?'/index.html':url.pathname;const file=normalize(join(root,pathname));if(!file.startsWith(root))return json(res,403,{error:'Forbidden'});try{const content=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(content)}catch{json(res,404,{error:'Not found'})}
});

server.listen(port,()=>{
  console.log(`CardScope is running at http://localhost:${port}`);
  if(process.env.CATALOG_SYNC_ON_START!=='false'&&supabaseConfigured())setTimeout(async()=>{try{const providers=await catalogProvidersNeedingSync(supabaseFetch,72);if(providers.length){console.log('starting scheduled catalog sync',providers.join(','));const result=await syncCatalog(supabaseFetch,{providers});console.log('scheduled catalog sync complete',JSON.stringify(result))}}catch(error){console.error('scheduled catalog sync failed',error.message)}},3000);
});

