// Run with PLAYWRIGHT_MODULE pointing to an installed Playwright index.mjs.
// Fixtures are intercepted in this test browser only; no catalog data is written.
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 const products=Array.from({length:10},(_,i)=>({id:`smoke-${i}`,game:'pokemon',region:'JP',catalogCategory:'原盒',officialCode:`M${6-i%3}`,nameZh:`測試商品 ${i}`,releaseDate:'2026-08-01',imageUrl:'/assets/brand/cardscope-rabbit-mark.png'}));
 const testCardSvg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 700"><rect width="500" height="700" rx="24" fill="#fff"/><rect x="12" y="12" width="476" height="676" rx="18" fill="#f7d63d" stroke="#222" stroke-width="12"/><rect x="42" y="54" width="416" height="510" fill="#52b7dd"/><rect x="42" y="584" width="416" height="70" fill="#cf3348"/><text x="250" y="630" text-anchor="middle" font-size="28">CARD BOTTOM</text></svg>';
 await page.route('https://images.pokemontcg.io/**',route=>route.fulfill({contentType:'image/svg+xml',body:testCardSvg}));
 await page.route('**/api/products',route=>route.fulfill({json:{data:products,series:[]}}));
 await page.addInitScript(()=>{localStorage.clear();localStorage.setItem('cardscope-recent-series','["smoke-0"]')});
 await page.goto(process.env.CARDSCOPE_URL||'http://localhost:4173');
 assert.equal(await page.locator('#cards .game-entry').count(),5);
 assert.equal(await page.locator('#cards .card').count(),0);
 await page.locator('#channels .channel').nth(1).click();
 await page.locator('#cards .card').first().waitFor();
 await page.locator('.active-series-block').waitFor();
 await page.locator('#cards .card').first().click();
 await page.locator('#modal.open .tilt-card').waitFor();
 await page.locator('#modal.open .tilt-card').click();
 await page.locator('#cardZoom.open img').waitFor();
 const zoomLayout=await page.evaluate(()=>{
  const viewport=document.querySelector('#cardZoom .card-zoom-viewport').getBoundingClientRect(),canvas=document.querySelector('#cardZoom .card-zoom-canvas').getBoundingClientRect(),toolbar=document.querySelector('#cardZoom .card-zoom-toolbar').getBoundingClientRect(),image=document.querySelector('#cardZoom .card-zoom-image');
  return {viewport:{top:viewport.top,bottom:viewport.bottom},canvas:{top:canvas.top,bottom:canvas.bottom},toolbar:{top:toolbar.top,bottom:toolbar.bottom},objectFit:getComputedStyle(image).objectFit};
 });
 assert.ok(zoomLayout.canvas.top>=zoomLayout.viewport.top&&zoomLayout.canvas.bottom<=zoomLayout.viewport.bottom,JSON.stringify(zoomLayout));
 assert.ok(zoomLayout.viewport.bottom<=zoomLayout.toolbar.top,JSON.stringify(zoomLayout));
 assert.equal(zoomLayout.objectFit,'contain');
 await page.locator('#cardZoom [data-zoom-preset="4"]').click();
 assert.equal(await page.locator('#cardZoom [data-zoom-label]').textContent(),'400%');
 await page.locator('#cardZoom .card-zoom-close').click();
 await page.locator('#close').click();
 assert.equal(await page.locator('.recent-series-details').getAttribute('open'),null);
 const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,series:document.querySelector('.active-series-block').getBoundingClientRect().x,cards:document.querySelector('#cards').getBoundingClientRect().y}));
 assert.ok(layout.series>=0&&layout.series<80,JSON.stringify(layout));
 assert.ok(layout.cards<900,JSON.stringify(layout));
 assert.ok(layout.scroll<=layout.width,JSON.stringify(layout));
 assert.ok(await page.locator('.brand-showcase img').evaluate(image=>image.complete&&image.naturalWidth>0),'Desktop mascot failed to load');
 const showcaseLayout=async()=>page.evaluate(()=>{
  const box=document.querySelector('.brand-showcase').getBoundingClientRect(),picture=document.querySelector('.brand-showcase picture').getBoundingClientRect(),copy=document.querySelector('.brand-showcase-copy').getBoundingClientRect(),button=document.querySelector('.brand-showcase button').getBoundingClientRect();
  return {box:{left:box.left,right:box.right,top:box.top,bottom:box.bottom},picture:{left:picture.left,right:picture.right,top:picture.top,bottom:picture.bottom},copy:{left:copy.left,right:copy.right,top:copy.top,bottom:copy.bottom},button:{left:button.left,right:button.right,top:button.top,bottom:button.bottom}};
 });
 const assertShowcaseFits=value=>{assert.ok(value.picture.right<=value.copy.left+1,JSON.stringify(value));assert.ok(value.copy.right<=value.box.right+1&&value.copy.bottom<=value.box.bottom+1,JSON.stringify(value));assert.ok(value.button.right<=value.box.right+1&&value.button.bottom<=value.box.bottom+1,JSON.stringify(value))};
 assertShowcaseFits(await showcaseLayout());
 await page.setViewportSize({width:900,height:900});
 assertShowcaseFits(await showcaseLayout());
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Tablet overflow');
 await page.locator('[data-favorite-id]').first().click();
 await page.locator('[data-watch-increment]').first().click();
 assert.match(await page.locator('#watchlistSummary').innerText(),/1 張、1 件/);
 assert.match(await page.locator('#brandCollectionToast img').getAttribute('src'),/rabbit-success\.jpg/);
 assert.equal(await page.locator('#brandCollectionToast').evaluate(node=>node.classList.contains('show')),true);
 await page.locator('#favoritesOnly').click();
 assert.equal(await page.locator('#cards .card').count(),1);
 await page.locator('#favoritesOnly').click();
 await page.locator('[data-view="rarity"]').click();
 await page.locator('.rarity-group').first().waitFor();
 assert.ok(await page.locator('.rarity-group').count()>0);
 await page.locator('[data-view="grid"]').click();
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
 assert.match(await page.locator('.brand-showcase img').evaluate(image=>image.currentSrc),/rabbit-hero-mobile\.jpg/);
 await page.locator('.mascot-gallery').evaluate(node=>node.open=true);
 assert.equal(await page.locator('.mascot-gallery figure').count(),7);
 assert.deepEqual(errors,[]);
 console.log('Browser smoke passed: default grid, card zoom/detail, desktop/recent rail, favorites, quantities, rarity groups, mobile overflow, zero JavaScript exceptions.');
}finally{await browser.close()}
