-- CardScope market data support
create table if not exists public.exchange_rates (
  id bigint generated by default as identity primary key,
  currency text not null,
  rate_to_twd numeric(18,8) not null check (rate_to_twd > 0),
  rate_date date not null,
  source text not null,
  fetched_at timestamptz not null default now(),
  unique (currency, rate_date)
);
create index if not exists exchange_rates_fetched_at_idx on public.exchange_rates (fetched_at desc);
alter table public.exchange_rates enable row level security;

create table if not exists public.card_images (
  id bigint generated by default as identity primary key,
  card_id text not null,
  language text,
  source text not null,
  image_url text not null,
  source_url text,
  is_primary boolean not null default false,
  fetched_at timestamptz not null default now(),
  unique (card_id, source, image_url)
);
create index if not exists card_images_card_id_idx on public.card_images (card_id);
create index if not exists card_images_primary_idx on public.card_images (card_id, is_primary desc);
alter table public.card_images enable row level security;
